### ISSUE TITLE
Improve read.me of this repository

### ISSUE THREAD

**Issue by juandiegocv27** [ByteBuildersLabs/ByteBeasts#11]
- Make this read.me more accesible and flexible based in the Lore of the game.
- Make the read.me easy to read for newcomers.

**Comment by jimenezz22** [comment]
@juandiegocv27 please add the following changes:

- Update title and description for something more related to the lore game
![Screenshot 2024-10-14 at 3 45 36 PM](https://github.com/user-attachments/assets/b285c5b9-dce0-49a9-825b-3218c8ad7fd7)

- Update Twitter link to the ByteBeasts account
- Update Creators to Founders and add our Everais PFP

![Screenshot 2024-10-14 at 3 47 08 PM](https://github.com/user-attachments/assets/efa9bf65-396c-4b93-bf37-cea3c748668f)

**Comment by juandiegocv27** [comment]
> @juandiegocv27 please add the following changes:
> 
> 
> 
> - Update title and description for something more related to the lore game
> 
> ![Screenshot 2024-10-14 at 3 45 36 PM](https://github.com/user-attachments/assets/b285c5b9-dce0-49a9-825b-3218c8ad7fd7)
> 
> 
> 
> - Update Twitter link to the ByteBeasts account
> 
> - Update Creators to Founders and add our Everais PFP
> 
> 
> 
> ![Screenshot 2024-10-14 at 3 47 08 PM](https://github.com/user-attachments/assets/efa9bf65-396c-4b93-bf37-cea3c748668f)
> 
> 
> 
> 
> 
> 

On my way sir🫡🥷🏻
